<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.barras.neptune</groupId>
		<artifactId>neptune</artifactId>
		<version>1.0.1a1</version>
	</parent>

	<artifactId>nfin</artifactId>
	<packaging>jar</packaging>

	<name>Finance</name>
	<description>Financial utility library for Python</description>
	<url>https://github.com/b-io/io.barras/tree/master/python/neptune/nfin</url>

	<!-- Project Settings -->
	<dependencies>
		<dependency>
			<groupId>io.barras.neptune</groupId>
			<artifactId>ngui</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.barras.neptune</groupId>
			<artifactId>nutil</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>

	<!-- Build Settings -->
	<build>
		<plugins>
			<!-- Execute the installation and test scripts -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
