<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.barras</groupId>
		<artifactId>io.barras</artifactId>
		<version>1.0.1a1</version>
	</parent>

	<groupId>io.barras.scala</groupId>
	<artifactId>io.barras.scala</artifactId>
	<packaging>pom</packaging>

	<name>Scala</name>
	<description>Libraries written in Scala</description>
	<url>https://github.com/b-io/io.barras/tree/master/scala</url>

	<properties>
		<!-- Scala -->
		<scala.version>2.13.16</scala.version>
		<scala.plugin.version>4.9.5</scala.plugin.version>
	</properties>

	<!-- Project Settings -->
	<modules>
		<module>saturn</module>
	</modules>

	<dependencies>
		<!-- Scala -->
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>${scala.version}</version>
		</dependency>
	</dependencies>

	<!-- Build Settings -->
	<build>
		<plugins>
			<!-- Compile Scala -->
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>scala-maven-plugin</artifactId>
				<version>${scala.plugin.version}</version>
				<configuration>
					<source>${maven.compiler.release}</source>
					<target>${maven.compiler.release}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
					<args>
						<arg>-deprecation</arg>
						<arg>-feature</arg>
					</args>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>testCompile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- Attach the sources -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
			</plugin>

			<!-- Attach the JavaDocs -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
